### ISSUE TITLE
RuntimeError: the vRA request did not create any servers.

### ISSUE THREAD

**Issue by Ronancunningham** [chef-partners/chef-provisioning-vra#2]
Hi

Im trying to use chef-provisioning-vra with requests for ec2 machines and I'm running into errors.

My machines ARE getting created correctly however chef is failing and reporting:

[2015-11-18T09:34:14+00:00] ERROR: machine[test1](@recipe_files::/Users/e19227/.chef/cookbooks/chef-provisioning/recipes/default.rb line 16) had an error: RuntimeError: the vRA request did not create any servers.
[2015-11-18T09:34:14+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

This is the same error I reported for kitchen-vra and vmware-vra-gem where support needed to be added for ec2 machines. 

https://github.com/chef-partners/kitchen-vra/issues/5#issuecomment-157073544

https://github.com/chef-partners/vmware-vra-gem/pull/5

I have installed that fix locally and it has fixed it for kitchen-vra but I still see the issue with chef-provisioning-vra.

Apologies, I'm just getting started with Ruby otherwise I would try and submit a fix.

thanks
Ronan

**Comment by adamleff** [comment]
@Ronancunningham:

The same logic in kitchen-vra is used in the chef-provisioning-vra driver to determine if a catalog request created any resources, so I suspect this is caused by you not actually using the branch of the vmware-vra gem that I provided in your other issue.

That said, I released a new version of that gem today (v1.5.0) that contains the change you validated.  On the host on which you're running chef-client/chef-provisioning, assuming you're using the Chef DK, please run:

`chef gem update vmware-vra`

You should see it get upgraded to v1.5.0.  That version contains the fix for the issue you're experiencing.

Thanks!
~Adam

**Comment by Ronancunningham** [comment]
Hi

Thanks again for the update:

**Comment by Ronancunningham** [comment]
Hi

I installed 1.5.0 but still got the same error.
I uninstalled vmware-vra 1.3.0 and 1.4.0 and found chef vra provisioning has a dependency on 1.3.0

LoadError: Could not find 'vmware-vra' (~> 1.3.0) - did find: [vmware-vra-1.5.0]

I tried manually updating the chef-provisioning-vra.gemspec, adding:

spec.add_dependency 'vmware-vra',            '~> 1.5.0'

However that didn't help, it still looks for 1.3.0.

I will troubleshoot further.

Thanks for your help

Ronan

**Comment by adamleff** [comment]
That's an error in the gemspec.  It should be `~> 1.3` not `~> 1.3.0`  I'll open a PR and cut a new release of chef-provisioning-vra with that change soon.

**Comment by adamleff** [comment]
PR #3 opened.

**Comment by adamleff** [comment]
v0.1.1 of chef-provisioning-vra has been released with a loosened version pin on vmware-vra-gem.  Your machine should now pull in vmware-vra-1.5.0 if it's available.
